sonar.projectKey=flask-app-devops
sonar.projectName=Flask App DevOps
sonar.projectVersion=1.0

sonar.sources=flask_app
sonar.sourceEncoding=UTF-8

sonar.python.version=3.9

sonar.tests=flask_app
sonar.test.inclusions=**/test_*.py
sonar.python.coverage.reportPaths=flask_app/coverage.xml
sonar.python.xunit.reportPath=flask_app/coverage.xml

sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc,**/htmlcov/**,**/.pytest_cache/**

sonar.python.bandit.reportPaths=flask_app/bandit-report.json

sonar.qualitygate.wait=true

sonar.python.pylint.reportPath=flask_app/pylint-report.txt

sonar.coverage.exclusions=**/test_*.py,**/venv/** 